# Generated by Django 3.2.8 on 2021-11-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_celerytasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='School2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1000000)),
                ('school_name', models.CharField(max_length=100)),
                ('udise_code', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('block', models.CharField(max_length=60)),
                ('cluster', models.CharField(max_length=60)),
                ('village', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('school_category', models.CharField(max_length=60)),
                ('school_type', models.CharField(max_length=60)),
                ('class_from', models.SmallIntegerField()),
                ('class_to', models.SmallIntegerField()),
                ('state_management', models.CharField(max_length=100)),
                ('national_management', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('aff_board_sec', models.CharField(max_length=60)),
                ('aff_board_hsec', models.CharField(max_length=60)),
                ('year_of_establishment', models.SmallIntegerField()),
                ('pre_primary', models.CharField(max_length=10)),
                ('building_status', models.CharField(max_length=60)),
                ('boundary_wall', models.CharField(max_length=60)),
                ('no_of_boys_toilets', models.SmallIntegerField()),
                ('no_of_girls_toilets', models.SmallIntegerField()),
                ('no_of_cwsn_toilets', models.SmallIntegerField()),
                ('drinking_water_availability', models.BooleanField(default=True)),
                ('hand_wash_facility', models.BooleanField(default=True)),
                ('functional_generator', models.SmallIntegerField()),
                ('library', models.BooleanField(default=True)),
                ('reading_corner', models.BooleanField(default=True)),
                ('book_bank', models.BooleanField(default=True)),
                ('functional_laptop', models.SmallIntegerField()),
                ('functional_desktop', models.SmallIntegerField()),
                ('functional_tablet', models.SmallIntegerField()),
                ('functional_scanner', models.SmallIntegerField()),
                ('functional_printer', models.SmallIntegerField()),
                ('functional_led', models.SmallIntegerField()),
                ('functional_digiboard', models.SmallIntegerField()),
                ('internet', models.BooleanField(default=True)),
                ('dth', models.BooleanField(default=True)),
                ('functional_web_cam', models.SmallIntegerField()),
                ('class_rooms', models.SmallIntegerField()),
                ('other_rooms', models.SmallIntegerField()),
                ('enrolment_of_the_students', models.CharField(max_length=60)),
                ('total_teachers', models.SmallIntegerField()),
            ],
        ),
    ]
