# Generated by Django 3.2.8 on 2021-11-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school2'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasks',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
