# Generated by Django 3.2.8 on 2021-11-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_celerytasks_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school2',
            name='national_management',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school2',
            name='school_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school2',
            name='state_management',
            field=models.CharField(max_length=200),
        ),
    ]
